
import { GoogleGenAI } from "@google/genai";

export const removeBackgroundGemini = async (
  apiKey: string, 
  imageBase64: string
): Promise<string> => {
  if (!apiKey) throw new Error("Gemini API Key is missing");

  const ai = new GoogleGenAI({ apiKey });
  
  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

  const prompt = `
    Task: Remove the background from this portrait photo.
    Output Requirement: Return ONLY the image bytes in PNG format.
    CRITICAL: The background MUST be completely transparent (Alpha channel 0). 
    Do NOT use white or any color for the background.
    Do NOT change the person's face, skin tone, or lighting.
    Do NOT include any text or explanations in the response.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            inlineData: { 
              mimeType: 'image/png', 
              data: cleanBase64 
            } 
          },
          { text: prompt },
        ],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/png;base64,${part.inlineData.data}`;
            }
        }
    }
    
    if (response.text) {
        console.warn("Gemini Text Response:", response.text);
        throw new Error("AI returned text instead of an image. Try again.");
    }

    throw new Error("No image generated by Gemini");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const removeBackgroundRemoveBg = async (
  apiKey: string, 
  imageBase64: string
): Promise<string> => {
  if (!apiKey) throw new Error("Remove.bg API Key is missing. Please add it in settings.");

  try {
      // Convert Data URI to Blob for robust upload (Fixes "Error reading image")
      const res = await fetch(imageBase64);
      const blob = await res.blob();

      const formData = new FormData();
      formData.append("image_file", blob);
      formData.append("size", "auto");
      
      const response = await fetch("https://api.remove.bg/v1.0/removebg", {
        method: "POST",
        headers: {
          "X-Api-Key": apiKey,
        },
        body: formData,
      });

      if (!response.ok) {
        const err = await response.json();
        const msg = err.errors?.[0]?.title || err.errors?.[0]?.code || "Unknown Error";
        throw new Error(`Remove.bg Error: ${msg}`);
      }

      const responseBlob = await response.blob();
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(responseBlob);
      });
  } catch (error: any) {
      console.error("Remove.bg API Error:", error);
      throw new Error(error.message || "Failed to connect to Remove.bg");
  }
};
